added jenkins/nexus integration
shelleg/ansible-role-juseppe pull request #1
Opened 2017-02-02 18:25 UTC by Chrislevi

@hagzag

2017-02-02 18:33 UTC, hagzag requested changes

2017-02-02 18:33 UTC, hagzag commented on tasks/get-plugins.yml
> +  when: cj_nexus
not the correct prefix in this role the variable prefix should be the role namespace ! which is juseppe_

2017-02-02 18:33 UTC, hagzag commented on tasks/get-plugins.yml
> +    url: "{{ plugin_url |d('http://mirrors.jenkins-ci.org') }}/plugins/{{ item.name }}/{{ item.version }}/{{ item.name }}.{{ item.extention | d('hpi') }}"
Same as my previous review the prefix should be the role name - what is plugin_url !?

2017-02-02 18:33 UTC, hagzag commented on tasks/set-plugin-list.yml
> +  when: (cj_wizard is not defined ) and (cj_wizard | bool)
This file looks exactly like the on in custom-jenkins role ... I can understand why here you would use the the cj_* for the plugins sets ... so I guess this one is OK

2017-02-02 19:06 UTC, Chrislevi commented on tasks/set-plugin-list.yml
> +  when: (cj_wizard is not defined ) and (cj_wizard | bool)
I tried to find a short resolution to merge dicts, but got into corners so I just used the one from jenkins.

2017-02-02 19:08 UTC, Chrislevi commented on tasks/get-plugins.yml
> +  when: cj_nexus
cj_nexus_url already exist and its inherited from group_vars, functionally its working. its a code cosmetic issue

2017-02-02 19:09 UTC, Chrislevi commented on tasks/get-plugins.yml
> +    url: "{{ plugin_url |d('http://mirrors.jenkins-ci.org') }}/plugins/{{ item.name }}/{{ item.version }}/{{ item.name }}.{{ item.extention | d('hpi') }}"
look at the set_fact in previous review. if cj_nexus trigger is true use the nexus url if not, use default which points to mirror.jenkins.org.

2017-02-02 19:11 UTC, Chrislevi commented
If you want to keep this role clean from inherited vars(cj_*) than I should push those changes to a side branch like the other repos.

2017-02-03 00:22 UTC, hagzag approved these changes

2017-02-03 00:23 UTC, merged